sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install jest babel-cli babel-preset-es2015 babel-preset-react
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - development
