sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install jest jest-util babel-cli babel-preset-es2015 babel-preset-react react react-test-renderer prop-types codecov.io coveralls
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - development
