language: node_js
node_js:
  - 8
cache: npm

before_install:
  - npm i -g npm@latest
  - npm install coveralls mocha chai react-dom enzyme-adapter-react-16 enzyme

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  -
deploy:
  provider: npm
  email: "cbartram3@gmail.com"
  api_key: NPM_TOKEN
  branches:
    only:
      - master
